import {
  Book,
  Wine,
  Home,
  Utensils,
  ShoppingBag,
  Map,
  Gamepad2,
  IceCream2,
  Building,
  GlassWater,
  Footprints,
  Smartphone,
  AlarmClock,
  Car,
  Sunrise,
  Croissant,
  MapPin,
  Camera,
  PenLine,
  Palette,
  Brush,
  Martini,
  ShoppingCart,
  Music,
  Dice5,
  Heart,
  Sparkles,
  Landmark,
  Gift,
  Coffee,
  Bike,
  Tent,
  Star,
  Film,
  Headphones,
  Guitar,
  Pizza,
  Cake,
  Plane,
  Train,
  Telescope,
  Flame,
  Moon,
  Umbrella,
  Ticket,
  Trophy,
  Puzzle,
  Compass,
  Sailboat,
  Mountain,
  Trees,
  Flower,
  Sun,
  CloudRain,
  Snowflake,
  Theater,
  Popcorn,
  Sandwich,
  Beer,
  Grape,
  Cherry,
  Apple,
  Salad,
  Soup,
  Egg,
  Mic,
  Radio,
  Tv,
  Monitor,
  BookOpen,
  Newspaper,
  Library,
  GraduationCap,
  Lightbulb,
  Target,
  Flag,
  Clock,
  DollarSign,
  MessageCircleHeart,
  ArrowDown,
  ArrowUp,
  Bookmark,
  Dices,
  Menu,
  X,
  Link,
  Share2,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Search,
  Anchor,
  Leaf,
  Candy,
  PartyPopper,
  Volleyball,
  Waves,
  Clapperboard,
  Scissors,
  Paintbrush,
  Pencil,
  NotebookPen,
  Armchair,
  // Candle doesn't exist in lucide-react, use Flame as fallback
  Glasses,
  HandHeart,
  Laugh,
  Gem,
  Crown,
  Ribbon,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  book: Book,
  wine: Wine,
  home: Home,
  utensils: Utensils,
  'shopping-bag': ShoppingBag,
  map: Map,
  gamepad: Gamepad2,
  'ice-cream': IceCream2,
  building: Building,
  'glass-water': GlassWater,
  footprints: Footprints,
  smartphone: Smartphone,
  'alarm-clock': AlarmClock,
  car: Car,
  sunrise: Sunrise,
  croissant: Croissant,
  'map-pin': MapPin,
  camera: Camera,
  'pen-line': PenLine,
  palette: Palette,
  brush: Brush,
  martini: Martini,
  'shopping-cart': ShoppingCart,
  music: Music,
  dice: Dice5,
  heart: Heart,
  sparkles: Sparkles,
  landmark: Landmark,
  gift: Gift,
  coffee: Coffee,
  bike: Bike,
  tent: Tent,
  star: Star,
  film: Film,
  headphones: Headphones,
  guitar: Guitar,
  pizza: Pizza,
  cake: Cake,
  plane: Plane,
  train: Train,
  telescope: Telescope,
  flame: Flame,
  moon: Moon,
  umbrella: Umbrella,
  ticket: Ticket,
  trophy: Trophy,
  puzzle: Puzzle,
  compass: Compass,
  sailboat: Sailboat,
  mountain: Mountain,
  trees: Trees,
  flower: Flower,
  sun: Sun,
  'cloud-rain': CloudRain,
  snowflake: Snowflake,
  theater: Theater,
  popcorn: Popcorn,
  sandwich: Sandwich,
  beer: Beer,
  grape: Grape,
  cherry: Cherry,
  apple: Apple,
  salad: Salad,
  soup: Soup,
  egg: Egg,
  microphone: Mic,
  radio: Radio,
  tv: Tv,
  monitor: Monitor,
  'book-open': BookOpen,
  newspaper: Newspaper,
  library: Library,
  'graduation-cap': GraduationCap,
  lightbulb: Lightbulb,
  target: Target,
  flag: Flag,
  clock: Clock,
  'dollar-sign': DollarSign,
  'message-circle-heart': MessageCircleHeart,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  bookmark: Bookmark,
  dices: Dices,
  menu: Menu,
  x: X,
  link: Link,
  share: Share2,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'external-link': ExternalLink,
  search: Search,
  anchor: Anchor,
  leaf: Leaf,
  candy: Candy,
  'party-popper': PartyPopper,
  volleyball: Volleyball,
  waves: Waves,
  clapperboard: Clapperboard,
  scissors: Scissors,
  paintbrush: Paintbrush,
  pencil: Pencil,
  'notebook-pen': NotebookPen,
  armchair: Armchair,
  candle: Flame,
  glasses: Glasses,
  'hand-heart': HandHeart,
  laugh: Laugh,
  gem: Gem,
  crown: Crown,
  ribbon: Ribbon,
  zap: Zap,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || Sparkles;
}

export { type LucideIcon };
